name: veda_app
description: Veda Dairy operational Flutter app for owner and staff.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.0
  share_plus: ^10.0.2
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.1.0
  razorpay_flutter: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
